### PR TITLE
Add "Odds and Ends" article - work in progress.

### PR DESCRIPTION
**Pull request by racke**
Just a number of things I'm running across which are not prominently documented.

### CODE REVIEW

**Comment by xsawyerx** [comment]
Ping? :)

**Comment by racke** [comment]
Echo ... I'm going to finish it this week.

**Comment by xsawyerx** [comment]
Another ping? :)

**Comment by racke** [comment]
On 12/01/2016 09:52 AM, Sawyer X wrote:
> Another ping? :)
> 

Sorry, overwhelmed with work at the moment.

Regards
        Racke

-- 
Ecommerce and Linux consulting + Perl and web application programming.
Debian and Sympa administration.

**Comment by racke** [comment]
Closing old PR.

**Pull request closed without merging**
